export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_ACCOUNTS_ERROR = "GET_ACCOUNTS_ERROR";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const CREATE_TOKEN = "CREATE_TOKEN";
export const GET_TOKEN = "GET_TOKEN";
export const CLEAR_TOKEN = "CLEAR_TOKEN";

//EXPENSES
export const GET_EXPENSES_BY_MONTH = "GET_EXPENSES_BY_MONTH";
export const GET_EXPENSES_FAILED = "GET_EXPENSES_FAILED";
